import { useState } from "react";
import api from "../services/api";
import toast from "react-hot-toast";

interface Question {
  id: number;
  question: string;
  type: string;
  hint: string;
}

interface ChatMessage {
  sender: "ai" | "user";
  text: string;
  feedback?: {
    score: number;
    feedback: string;
    model_answer: string;
  };
}

const Interview = () => {
  const [role, setRole] = useState<string>("Frontend Developer");
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentIdx, setCurrentIdx] = useState<number>(0);
  const [isStarted, setIsStarted] = useState<boolean>(false);
  const [userAnswer, setUserAnswer] = useState<string>("");
  const [chatHistory, setChatHistory] = useState<ChatMessage[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);

  const startInterview = async () => {
    setIsLoading(true);
    try {
      const response = await api.post("/interview/generate", { role });
      const fetchedQs = response.data.questions;
      setQuestions(fetchedQs);
      setIsStarted(true);
      setCurrentIdx(0);
      setUserAnswer("");
      
      // Start chat with first question
      setChatHistory([
        {
          sender: "ai",
          text: `Welcome to your mock interview for the ${role} domain! Here is your first question:\n\n"${fetchedQs[0].question}"\n\nHint: ${fetchedQs[0].hint}`
        }
      ]);
      toast.success("Mock interview started!");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate questions.");
    } finally {
      setIsLoading(false);
    }
  };

  const submitAnswer = async () => {
    if (!userAnswer.trim()) {
      toast.error("Please type your response before submitting.");
      return;
    }

    setIsLoading(true);
    const currentQuestionText = questions[currentIdx].question;
    const answerToEvaluate = userAnswer;

    // Add user's answer to chat list
    setChatHistory((prev) => [
      ...prev,
      { sender: "user", text: answerToEvaluate }
    ]);
    setUserAnswer("");

    try {
      const response = await api.post("/interview/feedback", {
        question: currentQuestionText,
        answer: answerToEvaluate
      });

      const feedbackResult = response.data;

      // Add AI feedback message
      setChatHistory((prev) => [
        ...prev,
        {
          sender: "ai",
          text: `Answer evaluated! You scored ${feedbackResult.score}/100.`,
          feedback: {
            score: feedbackResult.score,
            feedback: feedbackResult.feedback,
            model_answer: feedbackResult.model_answer
          }
        }
      ]);
    } catch (error) {
      console.error(error);
      toast.error("Failed to evaluate your answer.");
    } finally {
      setIsLoading(false);
    }
  };

  const nextQuestion = () => {
    const nextIdx = currentIdx + 1;
    if (nextIdx < questions.length) {
      setCurrentIdx(nextIdx);
      setChatHistory((prev) => [
        ...prev,
        {
          sender: "ai",
          text: `Here is question ${nextIdx + 1}:\n\n"${questions[nextIdx].question}"\n\nHint: ${questions[nextIdx].hint}`
        }
      ]);
    } else {
      toast.success("Interview completed! Great job practicing!");
      setIsStarted(false);
      setQuestions([]);
    }
  };

  return (
    <div style={{ flexGrow: 1, display: "flex", flexDirection: "column" }}>
      <div className="header-top">
        <div className="header-title-section">
          <h1>AI Interview Prep</h1>
          <p>Practice realistic, job-specific technical and behavioral questions.</p>
        </div>
      </div>

      {!isStarted ? (
        <div className="glass" style={{ padding: "40px", maxWidth: "600px", margin: "24px auto", textAlign: "center" }}>
          <h2 style={{ marginBottom: "20px" }}>Configure Your Session</h2>
          <div className="form-group" style={{ marginBottom: "24px", textAlign: "left" }}>
            <label className="form-label">Choose Your Domain or Role</label>
            <input
              className="form-input"
              value={role}
              onChange={(e) => setRole(e.target.value)}
              style={{ width: "100%", background: "#08060d" }}
              placeholder="Examples: Product Manager, Data Analyst, DevOps Engineer, React Native, Cybersecurity, Nursing"
            />
            <div style={{ marginTop: "8px", color: "var(--text-muted)", fontSize: "0.8rem", lineHeight: 1.4 }}>
              Enter any domain you want to practice. The questions will be generated by Gemini for that specific focus.
            </div>
          </div>
          <button className="btn btn-primary" onClick={startInterview} disabled={isLoading}>
            {isLoading ? "Generating Questions..." : "Start Mock Interview"}
          </button>
        </div>
      ) : (
        <div className="interview-layout">
          <div className="glass interview-sidebar">
            <h3 style={{ margin: "0 0 12px 0", color: "var(--text-title)", fontSize: "1rem" }}>Session Progress</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
              {questions.map((q, idx) => (
                <div
                  key={q.id}
                  style={{
                    padding: "10px 14px",
                    borderRadius: "6px",
                    background: idx === currentIdx ? "var(--accent-glow)" : "rgba(255,255,255,0.02)",
                    border: idx === currentIdx ? "1px solid var(--accent-color)" : "1px solid var(--border-color)",
                    fontSize: "0.85rem"
                  }}
                >
                  <div style={{ fontWeight: 600, color: idx === currentIdx ? "var(--accent-hover)" : "var(--text-main)" }}>
                    Question {idx + 1}
                  </div>
                  <div style={{ color: "var(--text-muted)", fontSize: "0.75rem", marginTop: "4px" }}>
                    {q.type.toUpperCase()}
                  </div>
                </div>
              ))}
            </div>
            <button
              className="btn btn-secondary"
              onClick={() => setIsStarted(false)}
              style={{ marginTop: "auto", fontSize: "0.8rem" }}
            >
              End Interview
            </button>
          </div>

          <div className="glass" style={{ padding: "24px", display: "flex", flexDirection: "column", gap: "20px" }}>
            <div className="chat-history" style={{ minHeight: "380px" }}>
              {chatHistory.map((msg, index) => (
                <div key={index} style={{ display: "flex", flexDirection: "column", width: "100%" }}>
                  <div className={`chat-bubble ${msg.sender}`}>
                    {msg.text.split("\n").map((line, lidx) => (
                      <span key={lidx}>{line}<br /></span>
                    ))}

                    {msg.feedback && (
                      <div className="chat-feedback-card">
                        <div style={{ display: "flex", alignItems: "center", gap: "8px", fontWeight: 700, margin: "8px 0 4px 0" }}>
                          <span
                            style={{
                              padding: "2px 8px",
                              borderRadius: "4px",
                              background: msg.feedback.score >= 70 ? "rgba(155,92,255,0.16)" : "rgba(255,255,255,0.08)",
                              color: msg.feedback.score >= 70 ? "var(--accent-hover)" : "var(--text-title)",
                              border: msg.feedback.score >= 70 ? "1px solid rgba(155,92,255,0.35)" : "1px solid var(--border-color)"
                            }}
                          >
                            Score: {msg.feedback.score}/100
                          </span>
                        </div>
                        <p style={{ color: "var(--text-main)", fontStyle: "italic", marginBottom: "8px" }}>
                          "{msg.feedback.feedback}"
                        </p>
                        <div style={{ background: "rgba(0,0,0,0.24)", padding: "10px", borderRadius: "6px", borderLeft: "3px solid var(--accent-color)" }}>
                          <div style={{ fontWeight: 600, fontSize: "0.75rem", color: "var(--accent-hover)", marginBottom: "4px" }}>
                            EXPERT SAMPLE ANSWER:
                          </div>
                          <span style={{ color: "var(--text-main)", fontSize: "0.8rem" }}>
                            {msg.feedback.model_answer}
                          </span>
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>

            {/* If the last message was a user answer evaluation, show Next Question button */}
            {chatHistory.length > 0 && chatHistory[chatHistory.length - 1].sender === "ai" && chatHistory[chatHistory.length - 1].feedback ? (
              <div style={{ display: "flex", justifyContent: "flex-end" }}>
                <button className="btn btn-primary" onClick={nextQuestion}>
                  {currentIdx === questions.length - 1 ? "Complete Interview" : "Proceed to Next Question"}
                </button>
              </div>
            ) : (
              <div className="chat-input-area">
                <textarea
                  className="chat-input"
                  placeholder="Type your detailed interview answer here..."
                  value={userAnswer}
                  onChange={(e) => setUserAnswer(e.target.value)}
                  disabled={isLoading}
                />
                <button
                  className="btn btn-primary"
                  onClick={submitAnswer}
                  disabled={isLoading || !userAnswer.trim()}
                  style={{ alignSelf: "flex-end", height: "56px", padding: "0 24px" }}
                >
                  {isLoading ? "Evaluating..." : "Submit Answer"}
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default Interview;
